### PR TITLE
fixing bug to delete idea in user profil page

### LINKED ISSUE #150: Bug suppression idée utilisateur

### PR DESCRIPTION
**Pull request by AurelOconnell**

### CODE REVIEW

**Review by Spolito24 — APPROVED** [review]

File: migrations/Version20230724085911.php [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+{
+    public function getDescription(): string
+    {
+        return '';
+    }
+
+    public function up(Schema $schema): void
+    {
+        // this up() migration is auto-generated, please modify it to your needs
+        $this->addSql('ALTER TABLE user CHANGE password password VARCHAR(100) NOT NULL, CHANGE firstname firstname VARCHAR(100) NOT NULL, CHANGE lastname lastname VARCHAR(100) NOT NULL, CHANGE department department VARCHAR(255) NOT NULL');
```
Comment (aldaitzwild) [inline migrations/Version20230724085911.php]: No limitation for the password

**Review by aldaitzwild — CHANGES_REQUESTED** [review]

File: migrations/Version20230724094655.php [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+{
+    public function getDescription(): string
+    {
+        return '';
+    }
+
+    public function up(Schema $schema): void
+    {
+        // this up() migration is auto-generated, please modify it to your needs
+        $this->addSql('ALTER TABLE user CHANGE password password VARCHAR(255) NOT NULL');
```
Comment (aldaitzwild) [inline migrations/Version20230724094655.php]: No you should'nt add a new migration, you should correct the previous one

**Review by aldaitzwild — CHANGES_REQUESTED** [review]

**Review by aldaitzwild — APPROVED** [review]
