### PR TITLE
Fix update entities asserts

### LINKED ISSUE #126: Limiter le nombre de caractères pour nom et prénom dans la modification admin

### LINKED ISSUE #127: Controller les Entities via les ASSERTS

### PR DESCRIPTION
**Pull request by benrcd**

### CODE REVIEW

**Review by AurelOconnell — APPROVED** [review]

File: src/Controller/PasswordController.php [hunk 1]
```diff
@@ -31,8 +31,11 @@ public function changePassword(Request $request, UserRepository $userRepository)
 
         $newPassword = $request->get('new-password');
 
+        if (strlen($newPassword) < 6) {
+            $this->addFlash('danger', 'La taille du mot de passe doit etre suppérieur à 6 caractères');
+        }
 
-        if (!empty($newPassword)) {
+        if (!empty($newPassword) && strlen($newPassword) > 6) {
```
Comment (aldaitzwild) [inline src/Controller/PasswordController.php]: Ok and if the password length is exactly 6, what does happen ?

**Review by aldaitzwild — CHANGES_REQUESTED** [review]

File: src/Controller/PasswordController.php [hunk 2]
```diff
@@ -31,8 +31,11 @@ public function changePassword(Request $request, UserRepository $userRepository)
 
         $newPassword = $request->get('new-password');
 
+        if (strlen($newPassword) < 6) {
+            $this->addFlash('danger', 'La taille du mot de passe doit etre supérieur à 6 caractères');
+        }
 
-        if (!empty($newPassword)) {
+        if (!empty($newPassword) && strlen($newPassword) >= 7) {
```
Comment (aldaitzwild) [inline src/Controller/PasswordController.php:38]: The suspens is unbearable ! What happens when you have a password with EXACTLY 6 characters !!!!?????

**Review by aldaitzwild — CHANGES_REQUESTED** [review]

File: src/Controller/PasswordController.php (hunk 2 above)
Comment (benrcd) [reply src/Controller/PasswordController.php:38]: WHATS IN THE BOX ?!????!!??

**Review by aldaitzwild — APPROVED** [review]
